title: GraphXplore User Guide
description: >-
  GraphXplore is a tool for visual data exploration, extracting and annotating metadata, as well as cleaning and 
  transforming your data.
favicon_ico: /graphxplore_icon.png
#logo: /graphxplore_icon.png
author: Louis Bellmann

callouts:
  note:
    title: Note
    color: purple
baseurl: /graphxplore

# Build settings
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs@v0.8.1
#theme: minima
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/slate@v0.2.0
markdown: kramdown

plugins:
  # - jekyll-feed
  - jekyll-remote-theme
  #- jekyll-theme-minimal
exclude:
  - frontend/