title: GraphXplore User Guide
description: >-
  GraphXplore is a tool for visual data exploration, extracting and annotating metadata, as well as cleaning and 
  transforming your data.

# Build settings
theme: minima
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-theme-minimal
exclude:
  - frontend/